version: "3"

services:
    app:
        build: .
        command: 'npm start'
        volumes:
            - .:/home/app
        ports:
            - 19000:19000
            - 19001:19001
            - 19002:19002
            - 19003:19003
